runtime: python39
entrypoint: gunicorn -b :$PORT backend:app
instance_class: F1

env_variables:
  FLASK_ENV: 'production'

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 1

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto
  secure: always
